version: 2

models:
    - name: epics_canon
      description: "List of Epics."
      columns:
          - name: epic_id
            description: "The primary key for this table."
            tests:
                - unique
                - not_null
          - name: key
            description: "Frontend ID for Jira Epics."
            tests:
                - unique
                - not_null
          - name: epic_name
            description: "Name/Title of the epic."
            tests:
                - not_null
          - name: description
            description: "Description of the epic."
          - name: reporter_id
            description: "Employee who owns the epic."
            tests:
                - not_null
          - name: assignee_id
            description: "Employee who is assigned this epic."
          - name: priority
            description: "Priority of the epic."
          - name: feature_id
            description: "Feature tied to the epic."
            tests:
                - not_null
          - name: project_id
            description: "Project the epic is tied to."
          - name: resolution
            description: "Resolution for the Epic."
            tests:
                - not_null
          - name: resolution_date
            description: "Date the issue was completed (timestamp)."
          - name: priority
            description: "FK referencing the priority of the epic."
          - name: created_date
            description: "Date the issue was created (timestamp)."
            tests:
                - not_null
          - name: resolution_date
            description: "Date the issue was closed (timestamp)."
          - name: last_updated_date
            description: "Date the issue was last updated (timestamp)."
            tests:
                - not_null
          - name: last_update_by_id
            description: "Employee who last updated the ticket."
            tests:
                - not_null
          - name: self_url
            description: "Url to the ticket website."
            tests:
                - unique
                - not_null
          - name: data_source
            description: "Source of this data row (Jira, Trello, etc)"
            tests:
                - not_null

    - name: issues_canon
      description: "Ticket table from the raw Jira Issues Api."
      columns:
          - name: issue_id
            description: "The primary key for this table."
            tests:
                - unique
                - not_null
          - name: key
            description: "Frontend ID for Jira Issue."
            tests:
                - unique
                - not_null
          - name: parent_id
            description: "Self-referencing ID of the parent issue."
            tests:
                - relationships:
                    to: ref('issues_canon')
                    field: issue_id
          - name: status_category_changed_date
            description: "Timestamp of when teh status changed."
          - name: time_spent
            description: "Time that was spent working on this issue (in seconds)."
          - name: project_id
            description: "FK referencing the Project the issue is tied to."
          - name: issue_type
            description: "Issue type of the ticket."
          - name: resolution
            description: "FK referencing the resolution status."
          - name: work_ratio
            description: "Percentage of work that has been logged against the issue vs the original estimate."
          - name: last_viewed_date
            description: "Timestamp of when the issue was last viewed."
          - name: resolved_date
            description: "Date of when the issue was completed (timestamp)."
          - name: created_date
            description: "Date the issue was created (timestamp)."
            tests:
                - not_null
          - name: due_date
            description: "Expected due date for the issue (timestamp)."
          - name: priority
            description: "FK referencing the priority of the issue."
          - name: original_estimate
            description: "The estimate of how much work this issue will take (in seconds)."
            tests:
                - not_null
          - name: remaining_estimate
            description: "The estimate of how much work is remaining (in seconds)."
            tests:
                - not_null
          - name: last_updated_date
            description: "Date the issue was last updated (timestamp)."
            tests:
                - not_null
          - name: last_update_by_id
            description: "Employee who last updated the ticket."
            tests:
                - not_null
          - name: status
            description: "FK referencing the Status of the ticket."
            tests:
                - not_null
          - name: summary
            description: "The tile of the ticket."
          - name: description
            description: "The issue description."
          - name: reporter_id
            description: "Employee who created the ticket."
          - name: assignee_id
            description: "Employee who is assigned to the ticket."
          - name: environment
            description: "Environment in which the issue occured."
            tests:
                - not_null
          - name: sprint_id
            description: "FK referencing the Sprint."
          - name: epic_id
            description: "Epic the issue is tied to."
            tests:
                - unique
                - not_null
                - relationships:
                    to: ref('epics_canon')
                    field: epic_id
          - name: self_url
            description: "Url to the ticket website."
            tests:
                - unique
                - not_null
          - name: data_source
            description: "Source of this data row (Jira, Trello, etc)"
            tests:
                - not_null

    - name: issue_field_history_canon
      description: "Ticket table from the raw Jira Issues Api."
      columns:
          - name: issue_field_history_id
            description: "Id of issue field history. (field_id + timestamp + employee_jira_id + index from change list)."
          - name: field_id
            description: "Referencing the field of the issue that was changed"
            tests:
                - not_null
          - name: issue_id
            description: "Foreign Key referring to the issue."
            tests:
                - not_null
                - relationships:
                    to: ref('issues_canon')
                    field: issue_id
          - name: time_changed
            description: "Timestamp of when the change occurred."
          - name: new_value
            description: "Value of the field it was changed to."
          - name: author_id
            description: "Employee who made the change"
